FROM python:3.10-slim

WORKDIR /build

RUN pip install --no-cache-dir build twine

COPY src ./src
COPY pyproject.toml ./
COPY README.md ./
COPY LICENSE ./

COPY .git ./.git

COPY versioning_script.sh /versioning_script.sh
RUN chmod +x /versioning_script.sh

ENTRYPOINT ["/versioning_script.sh"]