FROM python:3.10-slim

WORKDIR /build

RUN pip install --no-cache-dir build twine

COPY src ./src
COPY pyproject.toml ./
COPY README.md ./
COPY LICENSE ./

CMD ["bash", "-c", "python -m build && twine upload dist/*"]