FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir pip setuptools wheel
RUN pip install --no-cache-dir build


COPY pyproject.toml ./
COPY ./src ./src
RUN pip install --no-cache-dir ".[test]"
COPY ./tests ./tests


CMD ["pytest", "--maxfail=1", "--disable-warnings", "--tb=short"]
