name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies for linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 --config=.flake8 ./src ./tests

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting runs before tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run tests in Docker
        run: |
          docker-compose -f docker-compose.yaml run --rm test

  build:
    runs-on: ubuntu-latest
    needs: test  # Ensures tests pass before building and uploading
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Get the last Git tag
        id: git_tag
        run: |
          # Get the last Git tag (stable version)
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "0.1.0")
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
          echo "Last Git tag: $LAST_TAG"